spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/frame?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: 12345678
  redis:
    host: localhost
    password:
    port: 6379
    timeout: 5000
    database: 0

#============================ minio 配置 ==========================================
minio:
  endpoint: http://192.168.8.32:9000
  username: minioadmin
  password: minioadmin
  bucket-name: test

api:
  # 是否开启接口授权
  authority: false
  # 是否开启接口签名校验
  sign: true
  # 时间戳有效期2分钟 (ms)
  tstimeout: 120000
  # 签名有效期2分钟 (ms)
  signtimeout: 120000

